{
  "auth": {
    "response_time_ms": null,
    "status_code": null,
    "status": "failed",
    "error": "HTTPConnectionPool(host='localhost', port=8001): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018BFE0B0270>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"
  },
  "core": {
    "response_time_ms": null,
    "status_code": null,
    "status": "failed",
    "error": "HTTPConnectionPool(host='localhost', port=8002): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018BFE0B2030>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"
  },
  "ml": {
    "response_time_ms": 2033.39,
    "status_code": 200,
    "status": "success"
  },
  "payment": {
    "response_time_ms": 2274.48,
    "status_code": 200,
    "status": "success"
  },
  "overall_metrics": {
    "average_response_time_ms": 2153.93,
    "successful_services": 2,
    "total_services": 4,
    "success_rate": 50.0
  }
}